site_name: Conglomo US
plugins:
  - search
theme:
  name: material
  custom_dir: overrides
  static_templates:
    - 404.html
  palette:
    scheme: default
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.indexes
    - content.code.select
    - content.code.copy
    - content.code.annotate
    - navigation.sections
  palette:
    # Define custom primary and accent colors for the schemes
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
        # Ensure the automatic dark mode preference
  palette_toggle:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
  icon:
    admoniton:
      express: material/cards-diamond-outline # Add this line
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.details
  - admonition
  - def_list
  - tables
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
extra_css:
  - stylesheets/extra1.css